# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /opt/unreal-engine

TARGETS = \
	KBN_Project1-Android-DebugGame  \
	KBN_Project1-Android-Development  \
	KBN_Project1-Android-Shipping  \
	KBN_Project1-Linux-DebugGame  \
	KBN_Project1-Linux-Development  \
	KBN_Project1-Linux-Shipping  \
	KBN_Project1-LinuxArm64-DebugGame  \
	KBN_Project1-LinuxArm64-Development  \
	KBN_Project1-LinuxArm64-Shipping  \
	KBN_Project1 \
	KBN_Project1Editor-Linux-DebugGame  \
	KBN_Project1Editor-Linux-Development  \
	KBN_Project1Editor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend KBN_Project1Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug KBN_Project1Editor-Linux-Debug


KBN_Project1-Android-DebugGame:
	 $(BUILD) KBN_Project1 Android DebugGame  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-Android-Development:
	 $(BUILD) KBN_Project1 Android Development  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-Android-Shipping:
	 $(BUILD) KBN_Project1 Android Shipping  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-Linux-DebugGame:
	 $(BUILD) KBN_Project1 Linux DebugGame  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-Linux-Development:
	 $(BUILD) KBN_Project1 Linux Development  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-Linux-Shipping:
	 $(BUILD) KBN_Project1 Linux Shipping  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-LinuxArm64-DebugGame:
	 $(BUILD) KBN_Project1 LinuxArm64 DebugGame  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-LinuxArm64-Development:
	 $(BUILD) KBN_Project1 LinuxArm64 Development  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1-LinuxArm64-Shipping:
	 $(BUILD) KBN_Project1 LinuxArm64 Shipping  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1: KBN_Project1-Linux-Development

KBN_Project1Editor-Linux-DebugGame:
	 $(BUILD) KBN_Project1Editor Linux DebugGame  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1Editor-Linux-Development:
	 $(BUILD) KBN_Project1Editor Linux Development  -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" $(ARGS)

KBN_Project1Editor: KBN_Project1Editor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/tak_0/Documents/Unreal Projects/KBN_Project1/KBN_Project1.uproject" -Game 

.PHONY: $(TARGETS)
